# Generated by Django 4.1.7 on 2023-03-22 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=10000)),
                ('chat', models.ForeignKey(default='Chat.objects.get(id=2)', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='messages', to='core.chat')),
                ('user', models.ForeignKey(default='User.objects.get(id=2)', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
