# Generated by Django 4.1.7 on 2023-03-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_chat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.chat')),
                ('answered', models.BooleanField(default=False)),
            ],
            bases=('core.chat',),
        ),
    ]
