# Generated by Django 4.1.7 on 2023-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
